#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo-node-port
#spec:
#  type: NodePort
#  ports:
#    # Inside the cluster, what port does the service expose?
#    - port: 27017
#      # Which port do pods selected by this service expose?
#      targetPort: 27017
#      # Which port on the node the service is available through?
#      nodePort: 31517
#  selector:
#    component: mongodb
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: client-node-port
#spec:
#  type: NodePort
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 31515
#  selector:
#    component: web
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: server-node-port
#spec:
#  type: NodePort
#  ports:
#    # Inside the cluster, what port does the service expose?
#    - port: 5001
#    # Which port do pods selected by this service expose?
#      targetPort: 5001
#    # Which port on the node the service is available through?
#      nodePort: 31516
#  selector:
