apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
#  mongo.conf: |
#    storage:
#      dbPath: /data/db
  mongo-init.js: |
    print('mongo-init.js');
    const targetDbStr = cat('etc/mongo-init/MONGO_INITDB_DATABASE');
    const rootUser = cat('etc/mongo-init/MONGO_INITDB_ROOT_USERNAME');
    const rootPass = cat('etc/mongo-init/MONGO_INITDB_ROOT_PASSWORD');
    const defaultUser = cat('etc/mongo-init/MONGO_USERNAME');
    const defaultPassword = cat('etc/mongo-init/MONGO_PASSWORD');

    // auth against admin
    const adminDb = db.getSiblingDB('admin');
    adminDb.auth(rootUser, rootPass);
    print('Successfully authenticated admin user');

    // we'll create the users here
    const targetDb = db.getSiblingDB(targetDbStr);

    targetDb.createUser({
      user: defaultUser,
      pwd: defaultPassword,
      roles: [
        {
          role: "readWrite",
          db: targetDbStr
        }
      ]
    });
