apiVersion: v1
kind: Secret
metadata:
  name: mongo-config
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_INITDB_ROOT_PASSWORD: cm9vdFBhc3N3b3Jk
  MONGO_INITDB_DATABASE: bWVybg==
  MONGO_USERNAME: ZGVmYXVsdFVzZXI=
  MONGO_PASSWORD: ZGVmYXVsdFBhc3N3b3Jk
#  MONGO_USERS_LIST: dHJhaW5pbmc6ZGJBZG1pbixyZWFkV3JpdGU6cGFzc3dvcmQK
