#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongodb-deployment-persistent-volume
#spec:
#  capacity:
#    storage: 2Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: mongodb-deployment
#  local:
#    path: /mongo-init
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - mongodb-node
