kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-deployment-persistent-claim
spec:
#  storageClassName: mongodb-deployment-persistent-volume
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
